version: "3.3"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=ul+ql@t5#jod%am1!9&hoq7*$$%seh7s747(p$$8d!kr8nl3%_f*
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    # depends_on:
    #   - db
#   db:
#     image: postgres:11
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/

# volumes:
#   postgres_data:
